export const TriangleDistributionModes  = {
    LOW_TO_HIGH: 1,
    HIGH_TO_LOW: 2
};

export const SaimmConstants = {
    DEFAULT_DISTRUBUTION_SIZE: 50000,
    DEFAULT_DISTRUBUTION_START: -100,
    DEFAULT_DISTRUBUTION_END: 100,
    DEFAULT_INTERVALS_AMOUNT: 20,
    DEFAULT_BIG_ARRAY_STEP: 5,
    DEFAULT_M: 5,
    DEFAULT_D: 5,
    DEFAULT_GAUSSIAN_RANDOM_AMOUNT: 6,
    DEFAULT_EXPONENTIAL_LAMBDA: 0.5,
    DEFAULT_GAMMA_LAMBDA: 0.5,
    DEFAULT_GAMMA_N: 1,
    DEFAULT_TRIANGLE_MODE: TriangleDistributionModes.LOW_TO_HIGH,
    DEFAULT_D3_SELECTOR: '#smoSvg',
    ACTIVE_STATE_FILL: '#f2f2f2',
    NOT_ACTIVE_STATE_FILL: 'white'
};
